name: CI/CD Pipeline

on:
  push:
    branches:
      - develop

jobs:
  lint:
    name: Lint PHP files
    runs-on: [self-hosted]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run PHP Lint
        run: |
          for file in $(git ls-files "*.php"); do
            php -l "$file"
          done

  build:
    name: Build Docker Image
    runs-on: [self-hosted]
    needs: lint

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t yoyo338/nginx-junia:latest .

  push:
    name: Push Docker Image to Docker Hub
    runs-on: [self-hosted]
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password "${{ secrets.DOCKER_HUB_PASSWORD }}"

      - name: Push Docker image to Docker Hub
        run: |
          docker push yoyo338/nginx-junia:latest

  deploy:
    name: Deploy to Remote Server
    runs-on: [self-hosted]
    needs: push

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pull Docker images and start containers
        run: |
          if [ "$(docker ps -q -f name=nginx-SSH)" ]; then
              echo "Container 'nginx' is running. Stopping and removing it."
              docker stop nginx-SSH
              docker rm nginx-SSH
          else
              echo "Container 'nginx' is not running."
          fi
          ssh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << 'EOF'
            docker pull yoyo338/nginx-junia:latest
            docker run -d --name nginx-SSH -p 80:80 yoyo338/nginx-junia:latest
          EOF
